name: Build and Run USB Host test

on:
  schedule:
    - cron: '0 0 * * SAT' # Saturday midnight
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        idf_ver: ["latest"]
    runs-on: ubuntu-20.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build and Test
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          pip install pytest idf-build-apps==2.4.3 --upgrade
          idf-build-apps find --target linux
          idf-build-apps build --target linux
          chmod +x $GITHUB_WORKSPACE/run_host_tests.sh && $GITHUB_WORKSPACE/run_host_tests.sh
